name: Improved Theme Settings
type: module
description: Makes the theme pages a bit UI friendly for people with the permissions.
# core: 8.x
package: Custom

# Information added by Drupal.org packaging script on 2018-08-23
version: '8.x-2.4'
core: '8.x'
project: 'social'
datestamp: 1535037800
